{"name": "test_create_order_without_auth", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался код 401 при создании заказа без авторизации\nassert 200 == 401\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_orders.TestOrders object at 0x0000025C92CA4A50>\n\n    @allure.step(\"Тест создания заказа без авторизации\")\n    @pytest.mark.usefixtures(\"setup_without_auth\")\n    def test_create_order_without_auth(self):\n        ingredient_ids = [ingredient['_id'] for ingredient in self.ingredients['data'][:2]]\n        response = requests.post(\n            Endpoints.ORDERS,\n            json={'ingredients': ingredient_ids}\n        )\n        expected = ExpectedResponses.get_user_orders_failure()\n>       assert response.status_code == expected['status_code'], 'Ожидался код 401 при создании заказа без авторизации'\nE       AssertionError: Ожидался код 401 при создании заказа без авторизации\nE       assert 200 == 401\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\test_orders.py:42: AssertionError"}, "steps": [{"name": "Тест создания заказа без авторизации", "status": "failed", "statusDetails": {"message": "AssertionError: Ожидался код 401 при создании заказа без авторизации\nassert 200 == 401\n +  where 200 = <Response [200]>.status_code\n", "trace": "  File \"C:\\Users\\ReSnail\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"D:\\yandex\\Diplom_2\\tests\\test_orders.py\", line 42, in test_create_order_without_auth\n    assert response.status_code == expected['status_code'], 'Ожидался код 401 при создании заказа без авторизации'\n"}, "start": 1748559996218, "stop": 1748559996384}], "attachments": [{"name": "stdout", "source": "daeff0f3-c72b-4116-bad9-aeb3b439c6cd-attachment.txt", "type": "text/plain"}], "start": 1748559996218, "stop": 1748559996385, "uuid": "fe614dc9-40c1-45ff-b2c7-e3eeed4b5f82", "historyId": "a0ad7fc4e96bb54781437592a3bd2940", "testCaseId": "a0ad7fc4e96bb54781437592a3bd2940", "fullName": "tests.test_orders.TestOrders#test_create_order_without_auth", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_without_auth')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_orders"}, {"name": "subSuite", "value": "TestOrders"}, {"name": "host", "value": "FireWalker"}, {"name": "thread", "value": "36056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_orders"}]}